# VARIABLE AND DATATYPES

# VARIABLE DATA CAN STORE A VALUES
a = 30

# STRING NAME CAM STORE A VALUES IN VARIABLE
b = "Yash"

c = 70.12

# VARIABLE ARE USE TO STORE A DATATYPES LIKE A CONTAINER
print(type(c) , (b) , (a))