# TWO TYPE OF DATATYPE
# 1 - PRIMATIVE DATATYPE :- CAN BE MODIFY THE VALUES
# 2-NON PRIMATIVE DATATYPE :- CAN'T MODIFY AND EDIT THE VALUES AFTER CREATE

# 1- PRIMATIVE DATATYPE :-
# -> Integer
# -> FLOTING POINT NUMBER
# -> STRING
# -> BOOLEANS
# -> NONE

# PYTHON IS A FANTASTIC LANGUAGE THAT AUTOMATICALLY IDENTIFIES THE TYPE OF DATA FOR US
# EXAMPLE:-

_a = 25
b = 23.21
c = "Hello"
d = False
e = None

print(type(_a) , type(b) , type(c) , type(d) , type(e))

# SEE THE EXAMPLE USER CAN NOT DEFINE SEPRETLY INT,FLOAT ETC TYPE PYTHON AUTOMATICALY IDENTIFY THE DETAILS


